RepasoAJAX/Controllers/ProductoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RepasoAJAX.Controllers
{
    public class ProductoController : Controller
    {
        // GET: Producto
        public ActionResult ObtenerProducto(int? idProducto)
        {
            if (idProducto.GetValueOrDefault(0) > 0)
            {
                var result = BL.Producto.GetById(idProducto.Value);
                if (result.Item1)
                {
                    ML.Producto model = result.Item4;
                    var resultCategoria = BL.Categoria.GetAll();
                    var resultSubCategoria = BL.SubCategoria.GetAllByCategoria(model.Categoria.Categoria.IdCategoria);
                    model.Categoria.Categoria.Categorias = resultCategoria.Item1 ? resultCategoria.Item4.Categorias : new List<ML.Categoria>();
                    model.Categoria.Categorias = resultSubCategoria.Item1 ? resultSubCategoria.Item4.Categorias: new List<ML.SubCategoria>();
                    return View(model);
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                ML.Producto producto = new ML.Producto();
                var resultCategoria = BL.Categoria.GetAll();
                producto.Categoria = new ML.SubCategoria();
                producto.Categoria.Categorias = new List<ML.SubCategoria>();
                producto.Categoria.Categoria = new ML.Categoria();
                producto.Categoria.Categoria.Categorias = resultCategoria.Item1 ? resultCategoria.Item4.Categorias : new List<ML.Categoria>();
                return View(producto);
            }
        }
    }
}

RepasoAJAX/Views/Producto/ObtenerProducto.cshtml
@model ML.Producto
@{
    ViewBag.Title = "ObtenerProducto";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <div class="p-3 row justify-content-center align-items-center">
        @using (Html.BeginForm("ObtenerProducto", "Producto", FormMethod.Post, new { @id = "ActualizarForm", @class = "row g-3 w-50" }))
        {
            @Html.HiddenFor(model => model.Sku)
            <div class="col-md-auto">
                <div class="form-floating">
                    @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @placeholder = "" })
                    @Html.LabelFor(model => model.Nombre, new { @class = "" })
                </div>
            </div>
            <div class="col-md-auto">
                <div class="form-floating">
                    @Html.TextBoxFor(model => model.NumMateria, new { @class = "form-control", @placeholder = "" })
                    @Html.LabelFor(model => model.NumMateria, new { @class = "" })
                </div>
            </div>
            <div class="col-md-auto">
                <div class="input-group my-3">
                    @Html.LabelFor(model => model.Categoria.Categoria, new { @class = "input-group-text" })
                    @Html.DropDownListFor(model => model.Categoria.Categoria.IdCategoria, new SelectList(Model.Categoria.Categoria.Categorias, "IdCategoria", "Nombre", Model.Categoria.Categoria.IdCategoria), "Seleccione el area del producto", new { @class = "form-control", @id = "DDLCategoria" })
                </div>
            </div>
            <div class="col-md-auto">
                <div class="input-group my-3">
                    @Html.LabelFor(model => model.Categoria, new { @class = "input-group-text" })
                    @if (Model.Categoria.IdSubCategoria > 0)
                    {
                        @Html.DropDownListFor(model => model.Categoria.IdSubCategoria, new SelectList(Model.Categoria.Categorias, "IdSubCategoria", "Nombre", Model.Categoria.IdSubCategoria), "Seleccione una seccion", new { @class = "form-control", @id = "DDLSubCategoria" })
                    }
                    else
                    {
                        @Html.DropDownList("Categoria.IdSubCategoria", new SelectList(Model.Categoria.Categorias), "Seleccione una seccion", new { @class = "form-control", @id = "DDLSubCategoria" })
                    }
                </div>
            </div>
            <div class="col-md-auto">
                <div class="form-floating">
                    @Html.TextBoxFor(model => model.Inventario, new { @class = "form-control", @placeholder = "" })
                    @Html.LabelFor(model => model.Inventario, new { @class = "" })
                </div>
            </div>
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex">
                            <img id="imgProducto" src="~/Content/Assets/question.jpg" class="img-fluid rounded mx-auto d-block" />
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="row">
                            <input class="form-control w-100" type="file" id="ArchivoImg" />
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-12 d-flex justify-content-center align-items-center">
                <button type="submit" class="btn btn-info col" data-bs-toggle="modal" data-bs-target="#exampleModal" name="imgProducto">Ingresar nuevo producto</button>
            </div>
        }
    </div>
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="modalBody">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")